version: "3.9"

services:
  # nginx:
  #   container_name: chat_nginx
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #     - 443:443
  #   networks:
  #     - chat_dev
  #   volumes:
  #     - ./nginx/config/conf.d:/etc/nginx/conf.d
  #     - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: chat_keycloak
    restart: unless-stopped
    volumes:
      - ./keycloak/data/import:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin    
      KC_DB: "mysql"
      KC_DB_URL: 'jdbc:mysql://chat_mysql:3306/chat_keycloak'
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root      
      KC_HOSTNAME_STRICT: false
      KC_PROXY: edge
    # entrypoint: /opt/keycloak/bin/kc.sh start-dev 
    command: ["start-dev", "--import-realm"]
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - chat_dev
  db:
    container_name: chat_mysql
    image: mysql:8.0.35
    restart: unless-stopped
    volumes:
      - 'chat-mysql:/var/lib/mysql'
      - ./mysql/data/init-scripts:/docker-entrypoint-initdb.d      
      # - ./mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: chat
      MYSQL_PASSWORD: chat
    ports:
      - "3399:3306"
    networks:
      - chat_dev

  zookeeper:
    container_name: chat_zookeeper
    image: 'bitnami/zookeeper:latest'
    restart: unless-stopped
    networks:
      - chat_dev
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: chat_kafka
    image: 'bitnami/kafka:latest'
    restart: unless-stopped
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=CLIENT://:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://chat_kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=chat_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://chat_kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - chat_dev
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: chat_kafdrop
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: chat_kafka:9092
    networks: 
      - chat_dev
  
networks:
  chat_dev:
      
volumes:
  chat-mysql:
      driver: local

